Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -22,11 +22,11 @@ jobs:
       - name: Wait for API run
         run: sleep 10
 
-      #доступность адреса + состояние контейнеров
-      - name: Ping API
-        run: |
-          curl -X GET --fail http://127.0.0.1:3000 || exit 1
-          docker ps -a
+      # #доступность адреса + состояние контейнеров
+      # - name: Ping API
+      #   run: |
+      #     curl -X GET --fail http://127.0.0.1:3000 || exit 1
+      #     docker ps -a
 
       - name: check DB
         run: docker logs web-mariadb-16
